# Generated by Django 5.2.8 on 2025-12-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_options_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nome',
            new_name='payment_intent',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='endereco',
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_pago',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
