# Generated by Django 5.2.8 on 2025-12-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_nome_pedido_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='payment_intent',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
